import { z, defineCollection } from 'astro:content';

const recipeCollection = defineCollection({
    type: 'content',
    schema: ({ image }) => z.object({
        title: z.string(),
        subtitle: z.string(),
        image: image(),
        category: z.enum(["SideDish", "Salad", "Dressing"]),
        totalTime: z.string(),
        ingredients: z.array(z.object({
            key: z.enum([
                "almonds",
                "apple",
                "aubergine",
                "avocado",
                "bell-pepper",
                "butter",
                "cayenne",
                "chili",
                "chili-flakes",
                "chipotle-paste",
                "creme-vega",
                "vinegar",
                "spring-onion",
                "jalapeno",
                "lime-juice",
                "lime-zest",
                "corn",
                "mango",
                "mayonnaise",
                "miso",
                "honey",
                "carrot",
                "chickpeas",
                "garlic",
                "garlic-powder",
                "koriander",
                "cumin",
                "turmeric",
                "oil",
                "onion",
                "pak-choi",
                "paprika",
                "pepper",
                "salt",
                "sun-dried-tomatoes",
                "chives",
                "pointed-cabbage",
                "tahini",
                "tomato",
                "cinnamon",
                "sugar"
            ]),
            amount: z.string().optional(),
        })),
        source: z.string().optional(),
    }),
});

export const collections = {
    'recipes': recipeCollection,
};
